# Generated by Django 5.1.2 on 2025-11-20 15:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название аварии')),
                ('condition', models.CharField(choices=[('GT', 'Больше'), ('LT', 'Меньше'), ('EQ', 'Равно'), ('CHANGE', 'Изменение')], max_length=10, verbose_name='Условие')),
                ('trigger_value', models.FloatField(verbose_name='Пороговое значение')),
                ('message', models.TextField(verbose_name='Сообщение аварии')),
                ('severity', models.CharField(choices=[('LOW', 'Низкая'), ('MEDIUM', 'Средняя'), ('HIGH', 'Высокая'), ('CRITICAL', 'Критическая')], default='MEDIUM', max_length=10, verbose_name='Важность')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Определение аварии',
                'verbose_name_plural': 'Определения аварий',
            },
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип объекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип объекта',
                'verbose_name_plural': 'Типы объектов',
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время срабатывания')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Время квитирования')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Время сброса')),
                ('state', models.CharField(choices=[('ACTIVE', 'Активна'), ('ACKNOWLEDGED', 'Квитирована'), ('RESOLVED', 'Сброшена')], default='ACTIVE', max_length=15, verbose_name='Состояние')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Квитировал')),
                ('alarm_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scada.alarmdefinition', verbose_name='Определение аварии')),
            ],
            options={
                'verbose_name': 'Авария',
                'verbose_name_plural': 'Аварии',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название объекта')),
                ('index', models.CharField(max_length=50, verbose_name='Индекс объекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Местоположение')),
                ('km_mark', models.FloatField(blank=True, null=True, verbose_name='Километровая отметка')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scada.objecttype', verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Объект нефтепровода',
                'verbose_name_plural': 'Объекты нефтепровода',
                'unique_together': {('object_type', 'index')},
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название тега')),
                ('description', models.TextField(verbose_name='Описание')),
                ('data_type', models.CharField(choices=[('float', 'Float'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('string', 'String')], max_length=10, verbose_name='Тип данных')),
                ('engineering_units', models.CharField(blank=True, max_length=50, verbose_name='Единицы измерения')),
                ('min_value', models.FloatField(default=0.0, verbose_name='Минимальное значение')),
                ('max_value', models.FloatField(default=100.0, verbose_name='Максимальное значение')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('pipeline_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scada.pipelineobject', verbose_name='Объект нефтепровода')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='alarmdefinition',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scada.tag', verbose_name='Тег'),
        ),
        migrations.CreateModel(
            name='TagTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_template', models.CharField(max_length=100, verbose_name='Шаблон имени тега')),
                ('description_template', models.TextField(verbose_name='Шаблон описания')),
                ('data_type', models.CharField(choices=[('float', 'Float'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('string', 'String')], default='float', max_length=10, verbose_name='Тип данных')),
                ('engineering_units', models.CharField(blank=True, max_length=50, verbose_name='Единицы измерения')),
                ('min_value', models.FloatField(default=0.0, verbose_name='Минимальное значение')),
                ('max_value', models.FloatField(default=100.0, verbose_name='Максимальное значение')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scada.objecttype', verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Шаблон тега',
                'verbose_name_plural': 'Шаблоны тегов',
                'unique_together': {('object_type', 'name_template')},
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scada.tagtemplate', verbose_name='Шаблон тега'),
        ),
        migrations.CreateModel(
            name='TagValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('quality', models.IntegerField(default=100, verbose_name='Качество (0-100)')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Временная метка')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='scada.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Значение тега',
                'verbose_name_plural': 'Значения тегов',
                'ordering': ['-timestamp'],
            },
        ),
    ]
